spring:
  application:
    name: employee

  datasource:
    url: jdbc:h2:mem:testdb  # Use H2 in-memory database
#    url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=TRUE   # Use H2 in-memory database
    username: sa             # Default username for H2
    password: password       # Default password for H2 (you can change it)
    driver-class-name: org.h2.Driver
    platform: h2              # Specify the platform as H2

  jpa:
    hibernate:
      ddl-auto: update       # Auto-create database schema (can use create-drop for testing)
      dialect: org.hibernate.dialect.H2Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 9097
